name: Run Nightly Flaky Test Detector

on:
  schedule:
    # Run every night at 3:00 AM UTC
    - cron: '0 3 * * *'

jobs:
  trigger-flaky-test-detection:
    name: Find Flaky Tests
    uses: ./.github/workflows/find-new-flaky-tests.yml
    with:
      repoUrl: 'https://github.com/smartcontractkit/chainlink'
      baseRef: 'origin/develop'
      projectPath: '.'
      runThreshold: '1'
      runAllTests: 'true'
      extraArgs: '{ "skipped_tests": "TestChainComponents", "test_repeat_count": "5", "all_tests_runner": "ubuntu22.04-32cores-128GB", "all_tests_runner_count": "3", "min_pass_ratio": "0" }'
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.QA_SLACK_API_KEY }}
    